#!/bin/bash
set -e

[[ $1 == "" ]] && echo "Specify a hack to play. For example:" && echo "$ ./play hacks/example.h" && exit
# clang is not required, but it does a much better job at optimizing
clang++ -DHACK=$1 -lm -O2 -Wall -Wextra tinyspec.cpp -o tinyspec
./tinyspec | aplay -c2 -f FLOAT_LE -r 44100
